In [ ]:
Iterating : 

In [1]:
import numpy as np

In [ ]:
1D Array

In [3]:
a = np.arange(11)**2 # squaring operation...

In [4]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [5]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [7]:
students = np.array([['Alice','Beth','Cathy','Dorothy'], 
                    [65,78,90,81], 
                    [71,82,79,92]])

In [8]:
for i in students: # rows wise iteration....!
    print(' i =', i)

 i = ['Alice' 'Beth' 'Cathy' 'Dorothy']
 i = ['65' '78' '90' '81']
 i = ['71' '82' '79' '92']


In [ ]:
Flatten a multi-dimensional array :

In [ ]:
If one wants to perform an operation on each element in the array, one can use the flatten method which will flatten the 
array to a single n dimension. By default, the flattening will occur row-wise(also known as C order)

In [9]:
for element in students.flatten():  # using flatten row-wise iteration
    print(element)

Alice
Beth
Cathy
Dorothy
65
78
90
81
71
82
79
92


In [ ]:
flatten() which is global method in python where as iteration is a numpy method 

In [10]:
for x in students.flatten():  #  
    print(x)

Alice
Beth
Cathy
Dorothy
65
78
90
81
71
82
79
92


In [ ]:
Fortran order flattening : 

In [ ]:
To flatten a 2D array column-wise, use the Fortran order

In [12]:
for element in students.flatten(order = 'F'): # column based 
    print(element)

Alice
65
71
Beth
78
82
Cathy
90
79
Dorothy
81
92


In [ ]:
nditer : 

In [14]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
Default iteration behaviour is C order
This is row-wise iteration. similar to iterating over a C-order flattened array

In [15]:
for i in np.nditer(x): # np.nditer(x)
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
dtype = np.int16, dtype = np.int32 ====> typecasting

In [ ]:
Fortran Order : 
This is like iterating Over an array which has been flattened column-wise

In [17]:
for i in np.nditer(x, order = 'F'):
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [ ]:
Flags : 

In [ ]:
There are a number of flags which we can pass as a list to nditer, Many of these involve setting buffering options
if we want to iterate over each column, we can use this flag argument with value external loop.

In [18]:
for i in np.nditer(x, order = 'F', flags =['external_loop']):
    print(i)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [ ]:
Modifying Array Values : 

In [ ]:
By default, the nditer treats the input array as read-only object. To modify the array elements, you must specify either 
read-write or write-only mode. This is controlled with pre-operand flags.

In [ ]:
Writing on a read-only array results in an error

In [19]:
for arr in np.nditer(x):
    arr[...] = arr + arr

ValueError: assignment destination is read-only

In [ ]:
We set the ops_flag to make the array read-write

In [20]:
for arr in np.nditer(x, op_flags = ['readwrite']):
    arr[...] = arr + arr

In [21]:
x

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])