In [ ]:
Overview - NumPy : NumPy is a numerical computation library used for all the numerical calculations,

 and also for the scientific computation. It stands as a foundational library to all remaining libraries.

numpy stands for numerical python === Num - Py

we can also perform the statistical computing by using the numpy

Datatype of Numpy : NumPy is having a datatype called as ndarray

Overview of ndarray ====> number of dimensions array...

In [ ]:
Understanding :  Array is similar like a list.

Interview : what i sthe difference between an array and a list? if given a choice to you which one would you be preferring?

Array ===> internal implementation and working is very efficient in an array compared to list.

In [ ]:
# how to install numpy

In [4]:
!pip install numpy

In [ ]:
1.Create an array from a regular Python list or tuple using the array function

In [1]:
import numpy as np

In [2]:
array_one = np.array([1,2,3,4])
array_one

array([1, 2, 3, 4])

In [3]:
numbers = [9,8,7,6]
array_two = np.array(numbers)
array_two 

array([9, 8, 7, 6])

In [ ]:
2. NumPy offers several functions to create arrays with initial placeholder contnent

Create an array of zeros with desired shape (x,y)

* x == number of rows

* y == number of columns in array


In [5]:
array_of_zeroes = np.zeros((3,4))
array_of_zeroes 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
Note : internal implementation of an array is float (decimal numbers)

In [6]:
array_of_ones = np.ones((5,3))
array_of_ones 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# diff integer datatypes : 
int16, int32, int64

In [ ]:
Use dtype in order to specify the data type

In [13]:
array_of_ones_int = np.ones((3,4),dtype=np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [17]:
array_empty = np.empty((2,3))
array_empty

array([[2.27e-322, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000]])

In [ ]:
np.eye() creates an eyedentity matrix

In [18]:
array_eye = np.eye(5) # 5+5 matrix
array_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
3. To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists

arrange(start,stop,step,dtype)


In [20]:
array_of_evens = np.arange(2,20,2)
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
Note :  last value is always exclusive...